name: Deploy website

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
      - name: Install dependencies
        run: yarn install --immutable
      - name: Graphql codegen
        run: yarn gql:compile
      - name: Run build
        run: yarn build
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Rsync build to server and update symlink
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SITE_PATH: ${{ secrets.SITE_PATH }}
        run: |
          RELEASE_PATH="$SITE_PATH/releases/$(date +%Y_%m_%d_%H_%M_%S)"
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "mkdir -p $RELEASE_PATH"
          rsync -e 'ssh -p $SSH_PORT' -az --delete ./build/ $SSH_USER@$SSH_HOST:$RELEASE_PATH
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "ln -sfn $RELEASE_PATH $SITE_PATH/current"
          echo "✅ Deployed"
